FROM mcr.microsoft.com/devcontainers/go:2-1.25-trixie

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

RUN su vscode -c "curl -fsSL https://claude.ai/install.sh | bash"
